#!/bin/bash
if [ -z "$CODEC" ]
then
  # CODEC=huffyuv
  CODEC=libx264
fi

DESTINATION=$1
if [ -z "$DESTINATION" ]
then
  DESTINATION=rtmp://localhost/live/livestream
fi

CMD=" \
  -f x11grab \
	-i :0.0 \
	-preset ultrafast \
	-c:v ${CODEC} \
	-b:v 10M \
  -pix_fmt yuv420p \
  -f flv \
	$DESTINATION
"



echo ffmpeg $CMD
ffmpeg $CMD
